// Generator prompt (task 2026-09-04-001-T07).
//
// One call per planned file. What the model gets: the role, the boilerplate contract (rendered from
// the reference files by `exemplars.ts`, shared verbatim with the planner and repair prompts), the
// exemplar implementation for the kind of file it is writing, and the single task — with the
// contents of the files it depends on, because a generator that has to guess its own imports
// invents them.
//
// The rules live in the **system** turn and the ask lives in the **user** turn. That split is not
// cosmetic: the loop sends this prompt up to `--max-iterations` times per task with tool results
// appended, and a stable system turn is what keeps those calls cacheable and comparable in a trace.
//
// Nothing about the domain is written here. The task and the rules arrive as data, so a variant spec
// (T14) changes the prompt by changing the files it is pointed at.

import type { DerivedRules, Prompt } from "./exemplars.ts";
import { renderExemplars, renderRules } from "./exemplars.ts";

/**
 * One planned task, as produced by the planner (T08).
 *
 * Structurally the planner's schema keys, so a plan entry can be handed to this builder without a
 * mapping layer that could drift from either side.
 */
export interface GenerationTask {
  file: string;
  purpose: string;
  dependsOn?: string[];
  exports?: string[];
}

/** A file this task imports, already generated by an earlier task. Owned by the context builder (T09). */
export interface DependencyOutput {
  file: string;
  contents: string;
}

export interface GeneratorPromptInput {
  task: GenerationTask;
  /** The full spec, verbatim: a task is a slice of the requirements, not a replacement for them. */
  spec: string;
  rules: DerivedRules;
  /**
   * Contents of the dependency tasks' files. Optional because the hook is called for the first
   * tasks in the plan with nothing to show yet; a dependency named but absent is a planning bug the
   * loop reports, not something this builder papers over.
   */
  dependencyOutputs?: DependencyOutput[];
}

/** The job description, independent of which task is being generated. */
function generatorRole(): string {
  return [
    "You are the code-generation stage of an agent that builds one file at a time inside a React + TypeScript app.",
    "You write exactly one file per turn: the task's own file. You do not create, rename, edit or delete any other file, and you do not propose changes to the boilerplate the rules describe.",
    "You work through the sandboxed tools you were given. Call `write_file` once with the task's project-relative path and the complete contents of the file, then stop.",
    "Never narrate: no explanation, no diff, no summary outside the file you write.",
    "",
    "Quality bar for the file you write:",
    "- Complete and runnable. No placeholders, no TODO comments, no stubbed bodies, no commented-out work, no \"as any\", no empty catch blocks.",
    "- Typed for the strict compiler settings in the rules below, which means every declared symbol is used and every index access is narrowed.",
    "- Imports shared code from the modules the rules name instead of restating it, and imports nothing else from the reference tree.",
    "- Nothing beyond the task's stated purpose: the other tasks in the plan own the other behaviours.",
  ].join("\n");
}

/** The per-task turn: purpose first, then the contract it has to fit. */
function generatorUser(input: GeneratorPromptInput): string {
  const { task, spec, dependencyOutputs = [] } = input;
  const sections = [
    "Specification (the requirements this task is a part of):",
    "",
    spec.trim(),
    "",
    "Your task — write this one file:",
    `- file: ${task.file}`,
    `- purpose: ${task.purpose}`,
  ];
  if (task.dependsOn !== undefined && task.dependsOn.length > 0) {
    sections.push(`- depends on: ${task.dependsOn.join(", ")}`);
  }
  if (task.exports !== undefined && task.exports.length > 0) {
    sections.push(`- must export: ${task.exports.join(", ")}`);
  }

  if (dependencyOutputs.length > 0) {
    sections.push("", "Files already generated for the tasks you depend on. Import from them as written; do not restate them:");
    for (const output of dependencyOutputs) {
      sections.push("", `\`\`ts path="${output.file}"\n${output.contents}\`\`\``);
    }
  } else if (task.dependsOn !== undefined && task.dependsOn.length > 0) {
    sections.push(
      "",
      "No contents were supplied for the tasks you depend on, so import them by path and export name only.",
    );
  }

  sections.push(
    "",
    `Write \`${task.file}\` with \`write_file\`, satisfying the hard rules in your instructions, then stop.`,
  );
  return sections.join("\n");
}

/** Build the per-task generation request. */
export function buildGeneratorPrompt(input: GeneratorPromptInput): Prompt {
  const exemplars = renderExemplars(input.rules, input.task.file);
  const system = [
    generatorRole(),
    "",
    renderRules(input.rules),
    ...(exemplars === "" ? [] : ["", exemplars]),
  ].join("\n");

  return { system, messages: [{ role: "user", text: generatorUser(input) }] };
}
