// Executor prompt (tasks 2026-09-04-001-T07, re-pointed at the work skill).
//
// One call per task artifact. What the model gets: the role, the boilerplate contract (rendered
// from the reference files by `exemplars.ts`, shared verbatim with the planner and repair prompts),
// the exemplar implementation for the kind of file it is writing, the single task with its one
// Acceptance Criterion and Red -> Green -> Refactor steps, the contents of the files it depends on
// (a generator that has to guess its imports invents them), and the `work` skill's Execute phase as
// the binding procedure.
//
// The rules live in the **system** turn and the ask lives in the **user** turn. That split is not
// cosmetic: the loop sends this prompt up to `--max-iterations` times per task with tool results
// appended, and a stable system turn is what keeps those calls cacheable and comparable in a trace.
//
// Nothing about the domain is written here. The task, the rules and the skill arrive as data, so a
// variant spec (T14) changes the prompt by changing the files it is pointed at.

import type { DerivedRules, Prompt } from "./exemplars.ts";
import { renderExemplars, renderRules } from "./exemplars.ts";
import { workSkillBlock } from "../skill-prompts.ts";
import { DEFAULTS } from "../config.ts";
import { acceptanceCriterionFor, stepsFor, testFileFor } from "../plan-artifacts.ts";
import type { Task } from "../plan.ts";

/**
 * One planned task, as produced by the planner (T08) and executed as one work-skill task.
 *
 * Structurally the planner's schema keys, so a plan entry can be handed to this builder without a
 * mapping layer that could drift from either side. The optional keys are the plan skill's
 * Tasks-phase fields; when the planner omitted them the executor derives them, so the test-first
 * steps are always present.
 */
export interface GenerationTask extends Partial<Task> {
  file: string;
  purpose: string;
}

/** A file this task imports, already generated by an earlier task. Owned by the context builder (T09). */
export interface DependencyOutput {
  file: string;
  contents: string;
}

export interface GeneratorPromptInput {
  task: GenerationTask;
  /** The full spec, verbatim: a task is a slice of the requirements, not a replacement for them. */
  spec: string;
  rules: DerivedRules;
  /**
   * Contents of the dependency tasks' files. Optional because the hook is called for the first
   * tasks in the plan with nothing to show yet; a dependency named but absent is a planning bug the
   * loop reports, not something this builder papers over.
   */
  dependencyOutputs?: DependencyOutput[];
  /**
   * Skills directory carrying the `work` skill (default `.agents/skills`). The executor runs that
   * skill's Execute phase for this one task; pass an empty string to disable injection.
   */
  skillsDir?: string;
}

/**
 * Extras on top of the work skill's generic autopilot overrides, specific to this call.
 *
 * Nothing here talks about `docs/`: the boundary between this call and the repository is authored once,
 * in `skill-prompts.ts`, and restating it here is how the two copies drifted — the skill body promised
 * the model an index line under `docs/tasks/` that its sandbox can only refuse.
 */
function executorSkillRules(): string[] {
  return [
    "You cannot run the test suite from here: the output directory has no installed dependencies yet. The harness runs `npm run typecheck` and `npm run test` after you stop, so honour Red -> Green -> Refactor in the ORDER you write files — the task's test file first, the implementation second — rather than by executing them.",
  ];
}

/** The job description, independent of which task is being generated. */
function generatorRole(task: GenerationTask): string {
  const testFile = testFileFor(task);
  const ownsTestFile = testFile === task.file;
  const files = ownsTestFile
    ? `\`${task.file}\` — this task's file is its test`
    : `\`${testFile}\` (the task's test), then \`${task.file}\` (the implementation it proves)`;

  return [
    "You are the execution stage of a code-generation agent running one task of a plan at a time, inside a React + TypeScript app.",
    `You write only this task's own files: ${files}. You do not create, rename, edit or delete any other file, and you do not propose changes to the boilerplate the rules describe.`,
    ownsTestFile
      ? "You work through the sandboxed tools you were given: call `write_file` once with that path and the complete contents of the file, then stop."
      : "You work through the sandboxed tools you were given, in Red -> Green order: call `write_file` for the test file first, then call `write_file` for the implementation file, then stop. Never write the implementation before its test exists.",
    "Never narrate: no explanation, no diff, no summary outside the files you write.",
    "",
    "Quality bar for the files you write:",
    "- Complete and runnable. No placeholders, no TODO comments, no stubbed bodies, no commented-out work, no \"as any\", no empty catch blocks.",
    "- Typed for the strict compiler settings in the rules below, which means every declared symbol is used and every index access is narrowed.",
    "- Imports shared code from the modules the rules name instead of restating it, and imports nothing else from the reference tree.",
    "- Nothing beyond the task's stated purpose: the other tasks in the plan own the other behaviours.",
    "- The test asserts this task's Acceptance Criterion by behaviour, not by mirroring its own implementation.",
  ].join("\n");
}

/** The per-task turn: purpose and criterion first, then the contract it has to fit. */
function generatorUser(input: GeneratorPromptInput): string {
  const { task, spec, dependencyOutputs = [] } = input;
  const testFile = testFileFor(task);
  const [red, green, refactor] = stepsFor(task);
  const sections = [
    "Specification (the requirements this task is a part of):",
    "",
    spec.trim(),
    "",
    "Your task — write this file:",
    `- file: ${task.file}`,
    `- purpose: ${task.purpose}`,
  ];
  if (task.dependsOn !== undefined && task.dependsOn.length > 0) {
    sections.push(`- depends on: ${task.dependsOn.join(", ")}`);
  }
  if (task.exports !== undefined && task.exports.length > 0) {
    sections.push(`- must export: ${task.exports.join(", ")}`);
  }

  sections.push(
    "",
    "Acceptance Criterion (the one thing that has to be true when you stop):",
    "",
    acceptanceCriterionFor(task),
    "",
    "Steps, in this order:",
    "",
    `1. ${red}`,
    `2. ${green}`,
    `3. ${refactor}`,
    "",
    `Test file for this criterion: ${testFile}`,
  );

  if (dependencyOutputs.length > 0) {
    sections.push("", "Files already generated for the tasks you depend on. Import from them as written; do not restate them:");
    for (const output of dependencyOutputs) {
      sections.push("", `\`\`ts path="${output.file}"\n${output.contents}\`\`\``);
    }
  } else if (task.dependsOn !== undefined && task.dependsOn.length > 0) {
    sections.push(
      "",
      "No contents were supplied for the tasks you depend on, so import them by path and export name only.",
    );
  }

  sections.push(
    "",
    testFile === task.file
      ? `Write \`${task.file}\` with \`write_file\`, satisfying the hard rules and the work skill in your instructions, then stop.`
      : `Write \`${testFile}\` with \`write_file\` first, then \`${task.file}\`, satisfying the hard rules and the work skill in your instructions, then stop.`,
  );
  return sections.join("\n");
}

/** Build the per-task execution request: the task, its criterion, and the work skill's Execute phase. */
export function buildGeneratorPrompt(input: GeneratorPromptInput): Prompt {
  const exemplars = renderExemplars(input.rules, input.task.file);
  const skillBlock =
    input.skillsDir === "" ? "" : workSkillBlock(input.skillsDir ?? DEFAULTS.skillsDir, executorSkillRules());
  const system = [
    generatorRole(input.task),
    "",
    renderRules(input.rules),
    ...(exemplars === "" ? [] : ["", exemplars]),
    ...(skillBlock === "" ? [] : ["", skillBlock]),
  ].join("\n");

  return { system, messages: [{ role: "user", text: generatorUser(input) }] };
}
