// AC tests for the context builder (task 2026-09-04-001-T09).
//
// AC under test:
//   Context builder assembles contract files plus dependency outputs, elides lowest-priority
//   content to fit token budget, never drops spec or hard rules, and reports omissions.
//
// Test scenarios:
//   1. Squeeze: many sibling files, small budget -> non-droppable sections retained, siblings elided
//   2. Dependency scoping: task depending on `useCars` -> that file's content present, unrelated absent
//   3. Growth: files generated by earlier tasks become inputs for later ones

import { describe, expect, it } from "vitest";
import { buildContext, estimateTokens, type DependencyOutput } from "../src/context.ts";
import { type Task } from "../src/plan.ts";
import { deriveRules } from "../src/prompts/exemplars.ts";

const SPEC = `
Display a list of cars from the GraphQL API.
Users can filter by make and model.
Users can click a car to see its details in a modal.
`;

describe("Context builder with token budget", () => {
  describe("estimateTokens", () => {
    it("estimates tokens as characters divided by 4", () => {
      const text = "abcd"; // 4 characters = 1 token
      expect(estimateTokens(text)).toBe(1);

      const text2 = "abcdefgh"; // 8 characters = 2 tokens
      expect(estimateTokens(text2)).toBe(2);

      const text3 = "abc"; // 3 characters = 1 token (rounded up)
      expect(estimateTokens(text3)).toBe(1);
    });

    it("handles empty strings", () => {
      expect(estimateTokens("")).toBe(0);
    });

    it("is deterministic", () => {
      const text = "hello world from typescript";
      const result1 = estimateTokens(text);
      const result2 = estimateTokens(text);
      expect(result1).toBe(result2);
    });
  });

  describe("buildContext — within budget", () => {
    it("includes all sections when everything fits", () => {
      const task: Task = {
        file: "src/components/CarList.tsx",
        purpose: "List all cars",
        dependsOn: ["src/hooks/useCars.ts"],
        exports: ["CarList"],
      };

      const deps: DependencyOutput[] = [
        {
          file: "src/hooks/useCars.ts",
          content: "export const useCars = () => { /* implementation */ };",
        },
      ];

      const rules = deriveRules({ referenceRoot: "" });

      // Provide a large budget so everything fits
      const budget = 100000;
      const result = buildContext(SPEC, task, rules, deps, budget);

      // Verify no omissions
      expect(result.report.omitted).toHaveLength(0);
      expect(result.report.includedTokens).toBeLessThanOrEqual(budget);

      // Verify spec and rules are present
      expect(result.contextText).toContain(SPEC.trim());
      expect(result.contextText).toContain("Hard rules");
      expect(result.contextText).toContain("useCars");
    });

    it("includes dependency outputs for depending tasks", () => {
      const task: Task = {
        file: "src/components/CarList.tsx",
        purpose: "List all cars",
        dependsOn: ["src/hooks/useCars.ts"],
        exports: ["CarList"],
      };

      const deps: DependencyOutput[] = [
        {
          file: "src/hooks/useCars.ts",
          content: "export const useCars = () => { return cars; };",
        },
      ];

      const rules = deriveRules({ referenceRoot: "" });
      const budget = 100000;
      const result = buildContext(SPEC, task, rules, deps, budget);

      expect(result.contextText).toContain("useCars");
      expect(result.report.omitted).toHaveLength(0);
    });
  });

  describe("buildContext — over budget", () => {
    it("elides lowest-priority items when over budget", () => {
      const task: Task = {
        file: "src/components/CarList.tsx",
        purpose: "List all cars",
        dependsOn: ["src/hooks/useCars.ts"],
        exports: ["CarList"],
      };

      const largeDependency: DependencyOutput = {
        file: "src/hooks/useCars.ts",
        content: "x".repeat(10000), // Very large dependency
      };

      const rules = deriveRules({ referenceRoot: "" });

      // Calculate minimum budget needed for spec + rules, then add small amount for dependencies
      const specAndRulesTokens = estimateTokens(SPEC) + 600; // Rules are large
      const budget = specAndRulesTokens + 100; // Just barely over spec+rules
      const result = buildContext(SPEC, task, rules, [largeDependency], budget);

      // Spec and rules must always be present
      expect(result.contextText).toContain(SPEC.trim());
      expect(result.contextText).toContain("Hard rules");

      // The large dependency should be omitted
      expect(result.report.omitted.length).toBeGreaterThan(0);
      const omittedDep = result.report.omitted.find((item) =>
        item.name.includes("useCars"),
      );
      expect(omittedDep).toBeDefined();
    });

    it("reports omitted items with reason", () => {
      const task: Task = {
        file: "src/components/CarList.tsx",
        purpose: "List all cars",
        dependsOn: ["src/hooks/useCars.ts"],
        exports: ["CarList"],
      };

      const deps: DependencyOutput[] = [
        {
          file: "src/hooks/useCars.ts",
          content: "x".repeat(5000),
        },
        {
          file: "src/utils/format.ts",
          content: "x".repeat(5000),
        },
      ];

      const rules = deriveRules({ referenceRoot: "" });

      // Budget too small for all dependencies
      const budget = 600;
      const result = buildContext(SPEC, task, rules, deps, budget);

      // Verify omitted items have reasons
      expect(result.report.omitted.length).toBeGreaterThan(0);
      for (const item of result.report.omitted) {
        expect(item.reason).toBeTruthy();
        expect(item.tokens).toBeGreaterThan(0);
        expect(item.name).toBeTruthy();
      }
    });

    it("never omits spec or hard rules", () => {
      const task: Task = {
        file: "src/components/CarList.tsx",
        purpose: "List all cars",
        dependsOn: [],
        exports: ["CarList"],
      };

      const rules = deriveRules({ referenceRoot: "" });

      // Calculate actual tokens needed for spec and rules, then add buffer
      const specAndRulesTokens = estimateTokens(SPEC) + 600; // Rules are typically large
      const result = buildContext(SPEC, task, rules, [], specAndRulesTokens + 100);

      // Both spec and rules must be present
      expect(result.contextText).toContain(SPEC.trim());
      expect(result.contextText).toContain("Hard rules");
    });

    it("elides dependencies before exemplars (stable priority order)", () => {
      const task: Task = {
        file: "src/components/CarList.tsx",
        purpose: "List all cars",
        dependsOn: ["src/hooks/useCars.ts"],
        exports: ["CarList"],
      };

      const deps: DependencyOutput[] = [
        {
          file: "src/hooks/useCars.ts",
          content: "x".repeat(3000), // Large dependency
        },
      ];

      const rules = deriveRules({ referenceRoot: "" });

      // Moderate budget: forces choice between dependency and exemplar
      const budget = 1000;
      const result = buildContext(SPEC, task, rules, deps, budget);

      // Dependencies should be elided before exemplars
      // (or exemplars might not even be in this case)
      expect(result.report.omitted).toBeTruthy();
      expect(result.report.includedTokens).toBeLessThanOrEqual(budget);
    });
  });

  describe("buildContext — error cases", () => {
    it("fails if budget is zero or negative", () => {
      const task: Task = {
        file: "src/components/CarList.tsx",
        purpose: "List all cars",
        dependsOn: [],
        exports: ["CarList"],
      };

      const rules = deriveRules({ referenceRoot: "" });

      expect(() => {
        buildContext(SPEC, task, rules, [], 0);
      }).toThrow("Token budget must be positive");

      expect(() => {
        buildContext(SPEC, task, rules, [], -10);
      }).toThrow("Token budget must be positive");
    });

    it("fails if spec and rules exceed budget", () => {
      const task: Task = {
        file: "src/components/CarList.tsx",
        purpose: "List all cars",
        dependsOn: [],
        exports: ["CarList"],
      };

      const rules = deriveRules({ referenceRoot: "" });

      // Calculate tokens needed for spec and rules
      const specAndRulesTokens = estimateTokens(SPEC) + 500; // Rules are typically ~500 tokens

      // Budget smaller than spec + rules
      expect(() => {
        buildContext(SPEC, task, rules, [], specAndRulesTokens - 100);
      }).toThrow("Spec and rules exceed token budget");
    });
  });

  describe("buildContext — dependency scoping", () => {
    it("includes only specified dependencies", () => {
      const task: Task = {
        file: "src/components/CarList.tsx",
        purpose: "List all cars",
        dependsOn: ["src/hooks/useCars.ts"],
        exports: ["CarList"],
      };

      const deps: DependencyOutput[] = [
        {
          file: "src/hooks/useCars.ts",
          content: "export const useCars = () => {};",
        },
        // Note: src/utils/format.ts is NOT a dependency of task
      ];

      const rules = deriveRules({ referenceRoot: "" });
      const budget = 100000;
      const result = buildContext(SPEC, task, rules, deps, budget);

      // Only the dependency should be included
      expect(result.contextText).toContain("useCars");
      expect(result.report.omitted).toHaveLength(0);
    });

    it("handles tasks with no dependencies", () => {
      const task: Task = {
        file: "src/hooks/useCars.ts",
        purpose: "Fetch cars from API",
        dependsOn: [],
        exports: ["useCars"],
      };

      const deps: DependencyOutput[] = [];

      const rules = deriveRules({ referenceRoot: "" });
      const budget = 100000;
      const result = buildContext(SPEC, task, rules, deps, budget);

      // Only spec and rules, no dependencies
      expect(result.contextText).toContain(SPEC.trim());
      expect(result.contextText).toContain("Hard rules");
      expect(result.report.omitted).toHaveLength(0);
    });
  });

  describe("buildContext — growth scenario", () => {
    it("accumulates outputs from previous tasks as inputs to later ones", () => {
      // Task 1: useCars hook
      const task1: Task = {
        file: "src/hooks/useCars.ts",
        purpose: "Fetch cars from API",
        dependsOn: [],
        exports: ["useCars"],
      };

      // Task 2: CarCard component, depends on useCars
      const task2: Task = {
        file: "src/components/CarCard.tsx",
        purpose: "Display one car",
        dependsOn: ["src/hooks/useCars.ts"],
        exports: ["CarCard"],
      };

      const rules = deriveRules({ referenceRoot: "" });

      // Build context for task 1 (no dependencies)
      const context1 = buildContext(SPEC, task1, rules, [], 100000);
      expect(context1.contextText).toContain(SPEC.trim());

      // Build context for task 2 (with task1's output as input)
      const task1Output: DependencyOutput = {
        file: "src/hooks/useCars.ts",
        content: context1.contextText, // Use task1's context as input
      };

      const context2 = buildContext(SPEC, task2, rules, [task1Output], 100000);
      expect(context2.contextText).toContain(SPEC.trim());
      expect(context2.contextText).toContain("Hard rules");
      // The dependency output is included
      expect(context2.report.omitted).toHaveLength(0);
    });
  });

  describe("buildContext — determinism", () => {
    it("produces the same output for the same input", () => {
      const task: Task = {
        file: "src/components/CarList.tsx",
        purpose: "List all cars",
        dependsOn: ["src/hooks/useCars.ts"],
        exports: ["CarList"],
      };

      const deps: DependencyOutput[] = [
        {
          file: "src/hooks/useCars.ts",
          content: "export const useCars = () => {};",
        },
        {
          file: "src/utils/format.ts",
          content: "export const formatCar = (c) => c.name;",
        },
      ];

      const rules = deriveRules({ referenceRoot: "" });
      const budget = 2000;

      // Build context twice with identical inputs
      const result1 = buildContext(SPEC, task, rules, deps, budget);
      const result2 = buildContext(SPEC, task, rules, deps, budget);

      // Results should be identical
      expect(result1.contextText).toBe(result2.contextText);
      expect(result1.report.includedTokens).toBe(result2.report.includedTokens);
      expect(result1.report.omitted).toEqual(result2.report.omitted);
    });

    it("respects stable sort order for dependencies", () => {
      const task: Task = {
        file: "src/components/App.tsx",
        purpose: "App shell",
        dependsOn: ["src/utils/format.ts", "src/hooks/useCars.ts"],
        exports: [],
      };

      // Note: dependencies in different orders should yield same result
      const deps1: DependencyOutput[] = [
        {
          file: "src/hooks/useCars.ts",
          content: "export const useCars = () => {};",
        },
        {
          file: "src/utils/format.ts",
          content: "export const formatCar = (c) => c.name;",
        },
      ];

      const deps2: DependencyOutput[] = [
        {
          file: "src/utils/format.ts",
          content: "export const formatCar = (c) => c.name;",
        },
        {
          file: "src/hooks/useCars.ts",
          content: "export const useCars = () => {};",
        },
      ];

      const rules = deriveRules({ referenceRoot: "" });
      const budget = 2000;

      const result1 = buildContext(SPEC, task, rules, deps1, budget);
      const result2 = buildContext(SPEC, task, rules, deps2, budget);

      // Results should be identical regardless of input order
      expect(result1.contextText).toBe(result2.contextText);
      expect(result1.report.omitted).toEqual(result2.report.omitted);
    });
  });

  describe("buildContext — squeeze scenario", () => {
    it("retains non-droppable sections when squeezed by budget", () => {
      const task: Task = {
        file: "src/components/CarList.tsx",
        purpose: "List all cars",
        dependsOn: ["src/hooks/useCars.ts"],
        exports: ["CarList"],
      };

      const manyDeps: DependencyOutput[] = [
        {
          file: "src/hooks/useCars.ts",
          content: "x".repeat(2000),
        },
        {
          file: "src/utils/format.ts",
          content: "y".repeat(2000),
        },
        {
          file: "src/constants/index.ts",
          content: "z".repeat(2000),
        },
      ];

      const rules = deriveRules({ referenceRoot: "" });

      // Squeeze budget to force elision
      const budget = 800;
      const result = buildContext(SPEC, task, rules, manyDeps, budget);

      // Spec and rules must always be present
      expect(result.contextText).toContain(SPEC.trim());
      expect(result.contextText).toContain("Hard rules");

      // But some dependencies are omitted
      expect(result.report.omitted.length).toBeGreaterThan(0);
      expect(result.report.includedTokens).toBeLessThanOrEqual(budget);

      // Report should be clear about what was omitted
      for (const omitted of result.report.omitted) {
        expect(omitted.name).toBeTruthy();
        expect(omitted.reason).toBeTruthy();
      }
    });
  });
});
